### ISSUE TITLE
Missing dependency js-yaml

### ISSUE THREAD

**Issue by erdnaxeli** [matrix-org/matrix-appservice-slack#585] opened 2021-04-08 08:32 UTC
The lastest docker image (develop) seems to be missing a dependecy, even though it is listed in packages.json:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'js-yaml'
Require stack:
- /usr/src/app/node_modules/matrix-appservice/lib/app-service-registration.js
- /usr/src/app/node_modules/matrix-appservice/lib/index.js
- /usr/src/app/node_modules/matrix-appservice-bridge/lib/components/cli.js
- /usr/src/app/node_modules/matrix-appservice-bridge/lib/index.js
- /usr/src/app/lib/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/src/app/node_modules/matrix-appservice/lib/app-service-registration.js:8:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/matrix-appservice/lib/app-service-registration.js',
    '/usr/src/app/node_modules/matrix-appservice/lib/index.js',
    '/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/cli.js',
    '/usr/src/app/node_modules/matrix-appservice-bridge/lib/index.js',
    '/usr/src/app/lib/app.js'
  ]
}
```

**Comment by erdnaxeli** [comment] 2021-04-08 08:37
The package was added to dev dependency, I think this is wrong. And the PR (#583) didn't update the lockfile, although the package is already in it because it required by matrix-appservice-bridge.

**Comment by jaller94** [comment] 2021-04-08 12:51
It's a devDependency because it's only used in a test file.
https://github.com/matrix-org/matrix-appservice-slack/blob/8cebbed6d1d6ad32a3ccc18ebb8ee6ef609ea108/tests/unit/ConfigTest.ts#L17

I'll try to see why the file is being built in the docker image.

**Comment by jaller94** [comment] 2021-04-08 12:58
Command to reproduce the error message:
```
docker run --rm $(docker build --quiet .)
```

**Comment by jaller94** [comment] 2021-04-08 13:02
Issue seems to be fixed by just running `npm install`.

**Closed** 2021-04-09 12:17 UTC
Labels: bug
