### ISSUE TITLE
Messages from other apps in Slack (that use attachments) are silently ignored

### ISSUE THREAD

**Issue by fadenb** [matrix-org/matrix-appservice-slack#42] opened 2017-02-27 09:51 UTC
Hey,
just noticed that messages from apps like the RSS integration are silently ignored. This might be related to #37 as both are not ordinary messages.
This can cause confusing conversations when other team members refer to something that was posted by another app ;)

**Comment by MTRNord** [comment] 2017-04-20 18:18
Also other User that write via a App (/slack ghost user) aren't synced

**Comment by Vetgans** [comment] 2017-10-29 14:45
+1
Exactly the same issue as [fadenb](https://github.com/fadenb) describes.

Because the Riot Android app doesn't show images from it's own Matrix RSS-bot (see issue https://github.com/vector-im/riot-android/issues/1477), and the low priority this 'feature' was given, we tried to work around that problem by using the RSS integration in Slack. Only to find out that those RSS messages within Slack, are completely ignored by the Slack -> Matrix bridge. Not even a mention of a post, not in the Riot Android app nor in Riot-web.

The result is complete chaos in conversations, because Matrix users haven't got a clue what the discussions are about and don't know when a new chart is being discussed.

**Comment by erdnaxeli** [comment] 2017-12-05 23:28
This may be a limitation of the webhook API, I need to test.

**Comment by martindale** [comment] 2018-09-12 04:28
Any updates?

**Comment by Cadair** [comment] 2018-10-08 17:16
This appears to not be reproducible on develop when using the EventsAPI. There are issues with profile lookup (the bot doesnt have a name or avatar or anything) but at least it works.

**Comment by jbrinksmeier** [comment] 2019-01-13 10:39
@Cadair I did hit this with the EventsApi as well using a modular.im homeserver. I bridged a slack-channel that receives messages from another App (Datadog in this case). Bridging "normal" messages by regular slack-users does work, also messages by matrix users are visible in the slack channel. But the messages of the Datadog App are not visible in the matrix room at all.

**Comment by jbrinksmeier** [comment] 2019-01-13 16:33
I don't know for sure but would guess modular.im reuses some matrix.org infrastructure. I'll verify when I'm back to my computer, on the road right now.

**Comment by jbrinksmeier** [comment] 2019-01-13 20:47
Simply by looking at the requests tab in browser developer tools I see that scalar.vector.im integration manager is used, same as i riot.im. I think it's safe to then the matrix.org bridge is used? Otherwise I need to ask at modular.im directly.

**Comment by Cadair** [comment] 2019-01-14 14:54
Do you happen to know if the integration was using slack's attachment API?

**Comment by Cadair** [comment] 2019-01-14 14:56
While I agree that the specific datadog integration is out of scope, knowing which bit of the slack API we are not supporting would be useful. However, without seeing the event JSON I can't really be sure.

**Comment by jbrinksmeier** [comment] 2019-01-14 15:09
datadog's slack integration is closed source, but by the ui I can tell that they do use attachments. I have no way to access the actual event's json, sadly. Hope this helps anyway. Is there a known issue with the attachments api?

**Comment by Cadair** [comment] 2019-01-14 15:10
Do the messages on the slack side look like any of the examples here: https://api.slack.com/docs/message-attachments that would be a good start.

There isn't an issue for it, but I opened a PR with a quick fix #120

**Comment by jbrinksmeier** [comment] 2019-01-14 15:16
Yes it's exactly like that, even "worse" as there is actually no plaintext-part (like "Attachment pretext" in your example) at all.

**Comment by jbrinksmeier** [comment] 2019-02-06 05:54
hi @Cadair I gave your branch a try and can confirm it works for my use cases. Nice work, thank you. Would be cool if you find the time to finish the PR.

**Comment by Half-Shot** [comment] 2019-10-07 23:00
Closing in favour of #127

**Closed by Half-Shot** 2019-10-07 23:00 UTC
Labels: bug
