### ISSUE TITLE
Provide a way to promote another user to admin in a automatically provisioned room

### ISSUE THREAD

**Issue by Cadair** [matrix-org/matrix-appservice-slack#532] opened 2020-10-07 11:55 UTC
So that you can later kick the bridge out and retain control of the room

**Comment by psrpinto** [comment] 2021-11-29 16:38
Related to/duplicate of https://github.com/matrix-org/matrix-appservice-slack/issues/496

**Comment by jaller94** [comment] 2022-05-19 11:45
Closing as duplicate of https://github.com/matrix-org/matrix-appservice-slack/issues/496

**Closed by jaller94** 2022-05-19 11:45 UTC
Labels: duplicate, T-Enhancement
