### ISSUE TITLE
Integration times out

### ISSUE THREAD

**Issue by nukeador** [matrix-org/matrix-appservice-slack#637] opened 2021-11-12 13:52 UTC
Creating a new room and trying to add the Slack integrations results in a time out when selecting the slack channel.

![imagen](https://user-images.githubusercontent.com/531906/141477726-91226b24-dc50-4569-8e32-c412b9fb81d8.png)

**Comment by jaller94** [comment] 2021-11-15 16:05
This is an in-browser timeout to another tab which should ask your to authenticate to Slack.
It's using the [`window.postMessage()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) API.

Your JavaScript console should contain an associated error line like:
`postMessage request timed out. Sent object: `

Did you see a popup or new browser tab open? Did you see a popup blocker message in your browser?

**Comment by abmantis** [comment] 2021-11-17 00:35
@jaller94 No, there are no popups being shown or blocked. 
I do get a postMessage timeout:

![image](https://user-images.githubusercontent.com/974569/142088090-611886cd-42dc-4385-b55b-4c3147f53dc2.png)

**Comment by nukeador** [comment] 2021-11-25 10:47
The problem is still present, other people seems to be facing this and unable the create new bridges.

**Comment by psrpinto** [comment] 2021-12-02 12:52
I think this might be a duplicate of https://github.com/matrix-org/matrix-appservice-slack/issues/622

Probably fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7179, which isn't released as of writing this comment, but the fix is available at https://develop.element.io.

I was having this issue too and was able to get it working using https://develop.element.io

**Comment by jaller94** [comment] 2021-12-02 13:03
Correct, it's a bug in matrix-react-sdk. A fix has been merged and will likely land in Element Web/Desktop 1.9.6.

Upstream issue: https://github.com/vector-im/element-web/issues/19845

**Comment by mairin** [comment] 2021-12-02 17:42
I just tried develop.element.io to see if I could get it working there and it failed, but I was attempting to add a slack bridge to a matrix channel on fedora.im. Guessing maybe fedora.im needs to receive the update before it'll work

**Comment by abmantis** [comment] 2021-12-02 19:01
I tried with develop.element.io and it indeed works on matrix.org

**Comment by Half-Shot** [comment] 2022-05-16 10:19
I think this was since fixed.

**Closed by Half-Shot** 2022-05-16 10:19 UTC
