### ISSUE TITLE
Messages from slackbots in slack-channels cannot be relayed to matrix

### ISSUE THREAD

**Issue by schbrongx** [matrix-org/matrix-appservice-slack#127] opened 2019-05-09 11:46 UTC
User's messages are relayed just fine. I also have a Grafana-Monitoring bot joined which can post alers into the linked slack-channel. Those messages throw errors:

```
May-9 13:41:06.049 DEBUG SlackEventHandler Received slack event: {
  token: 'vL7Hr8hSKVzQ6ZIFoLxZusIE',
  team_id: 'TJLD12J31',
  api_app_id: 'AJLD7LSKZ',
  event: {
    type: 'message',
    subtype: 'bot_message',
    text: '',
    ts: '1557402065.005600',
    bot_id: 'BJ79AKDR8',
    attachments: [ [Object] ],
    channel: 'CJC7XACQ1',
    event_ts: '1557402065.005600',
    channel_type: 'channel'
  },
  type: 'event_callback',
  event_id: 'EvJ78XJB27',
  event_time: 1557402065,
  authed_users: [ 'UJ75H9HCJ' ]
}
May-9 13:41:06.053 ERROR SlackEventHandler SlackEventHandler.handle failed: ReferenceError: message is not defined
    at SlackEventHandler.handleMessageEvent (/var/lib/matrix-slack/lib/SlackEventHandler.js:188:63)
    at SlackEventHandler.handle (/var/lib/matrix-slack/lib/SlackEventHandler.js:54:31)
    at IncomingMessage.<anonymous> (/var/lib/matrix-slack/lib/SlackHookHandler.js:77:35)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

```

**Comment by auscompgeek** [comment] 2019-06-25 08:55
It looks like the bridge is assuming that Slack messages have text, which is [not necessarily true](https://api.slack.com/methods/chat.postMessage#arguments) when the message has [attachments](https://api.slack.com/docs/message-attachments).

**Comment by auscompgeek** [comment] 2019-06-25 08:56
I think this might be a duplicate of #42.

**Comment by Half-Shot** [comment] 2019-10-07 22:59
I believe this is fixed?

**Comment by auscompgeek** [comment] 2019-10-12 01:43
I'd say so too.

**Closed** 2019-10-12 09:41 UTC
